file_length: 350
function_body_length: 50
function_parameter_count: 5
line_length: 150
disabled_rules: # rule identifiers to exclude from running
 - force_cast
 - todo
 - weak_delegate
 - class_delegate_protocol
 - type_name
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
identifier_name:
 excluded: # excluded via string array
  - id
nesting:
  type_level: 3
attributes:
  always_on_same_line:
    - "@IBSegueAction"
    - "@IBAction"
    - "@NSManaged"
    - "@objc"
private_over_fileprivate:
  validate_extensions: true
opt_in_rules:
  - implicit_return
