file_length: 400
function_body_length: 50
function_parameter_count: 5
line_length: 150
disabled_rules: # rule identifiers to exclude from running
 - force_cast
 - trailing_whitespace
 - discarded_notification_center_observer
 - todo
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
identifier_name:
 excluded: # excluded via string array
  - id
nesting:
  type_level: 3