language: swift
osx_image: xcode11.0
xcode_workspace: UpcomingMovies.xcworkspace # path to your xcodeproj folder
xcode_scheme: UpcomingMovies
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPad Pro (9.7-inch)
before_install:
  - pod repo update
