language: swift
cache: cocoapods
osx_image: xcode12.2
xcode_destination: platform=iOS Simulator,OS=14.0,name=iPad Pro (9.7-inch)
before_install:
  - bundle install
install:
  - pod install
scripts:
  - fastlane lint
  - fastlane tests
