workflows:
  macos-workflow:
    name: iOS Workflow
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install pods
        script: |
          pod install
      - name: Run unit tests
        script: |
          bundle exec fastlane tests
