name: Swift

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  swiftLint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Bundle
      run: bundle install
    - name: Dependencies
      run: pod install
    - name: Run swiftlint
      run: bundle exec fastlane lint

  unitTests:
    needs: swiftLint
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Bundle
      run: bundle install
    - name: Dependencies
      run: pod install
    - name: Run unit tests
      run: bundle exec fastlane tests
