name: Testing

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  lint:
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '12.5'
    - uses: actions/checkout@v2
    - name: Install Bundle
      run: bundle install
    - name: Dependencies
      run: pod install
    - name: Run swiftlint
      run: bundle exec fastlane lint

  test:
    needs: lint
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '12.5'
    - uses: actions/checkout@v2
    - name: Install Bundle
      run: bundle install
    - name: Dependencies
      run: pod install
    - name: Run unit tests
      run: bundle exec fastlane tests
