name: Testing

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  lint:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Install Bundle
      run: bundle install
    - name: Dependencies
      run: pod install
    - name: Run swiftlint
      run: bundle exec fastlane lint

  test:
    needs: lint
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Install Bundle
      run: bundle install
    - name: Dependencies
      run: pod install
    - name: Run unit tests
      run: bundle exec fastlane tests
    - name: Generate lcov File
      run: |
        xcrun llvm-cov report $BUILD_FOLDER -instr-profile $PROFDATA_FOLDER
        xcrun llvm-cov export -format="lcov" $BUILD_FOLDER -instr-profile $PROFDATA_FOLDER > $LCOV_PATH
    - name: Upload coverage
      uses: codecov/codecov-action@v3
